### ISSUE TITLE
Incompatiblity issue with httpclient latest version from springweb-6.0 when used with token-client-3.0.1

### ISSUE THREAD

**Issue by kiranbadala** [SAP/cloud-security-services-integration-library#1216]
Incompatiblity issue with httpclient latest version from springweb-6.0 when used with token-client-3.0.1 because, springweb-6.0.9 uses latest httpclient and token client uses old httpclient library.

**Issue Summary**
-  Compilation fails when upgraded our spring module to 6.0.9 and token-client-3.0.1
- upgraded our spring module to 6.0.9 and token-client-3.0.1
- Compilation should be succesfull
- compilation failed
-  Compilation Error message : incompatible types: org.apache.http.impl.client.CloseableHttpClient cannot be converted to org.apache.hc.client5.http.classic.HttpClient

Code sample: 

 HttpComponentsClientHttpRequestFactory requestFactory = new HttpComponentsClientHttpRequestFactory();
	    requestFactory.setHttpClient(
	        HttpClientFactory.create(certificateClientIdentity));

**Issue Report Checklist**

- [x] Real, current bug
- [x] Not a duplicate  
- [x] Not covered in "Common Pitfalls" section of corresponding module's README.md e.g. [java-security#common-pitfalls](https://github.com/SAP/cloud-security-services-integration-library/tree/main/java-security#common-pitfalls)
- [x] Reproducible
- [x] Good summary
- [x] Well-documented 
    - [x] log level increased to `DEBUG` debug logs provided
    - [x] POM provided
    - [x] dependency tree provided
    - [x] code snippet provided (when applicable)

**Comment by finkmanAtSap** [comment]
Hi Kiran,

The http client that we create is intended for use inside the token-client module only.
It is not meant to be used for arbitrary spring requests.
However, you are free to create an HTTP client 5 yourself if you need it.
You can check our [DefaultHttpClientFactory](https://github.com/SAP/cloud-security-xsuaa-integration/blob/a950b721a0596d6ece95c6669e5c172c88b4a5f7/token-client/src/main/java/com/sap/cloud/security/client/DefaultHttpClientFactory.java#L43) to see how we did it.

Are the token flow classes of token-client module not enough for your use case or why are you creating request objects manually?

We decided to stay with apache http client 4 for some longer, even in version 3 of this library, because colleagues from CAP kindly asked us to in order to prevent lots of work on their side.

Best,
Manuel

**Comment by liga-oz** [comment]
Closing due to inactivity
